boundary_box:
  lat_min: 61
  lat_max: 68
  lon_min: -30
  lon_max: -10
  depth_min: 20
  depth_max: 250

date_range:
  start_date: '2010-01-01'
  end_date: '2025-08-31'

directories:
  data_dir: 'rawdata/copernicus'
  temp_dir: 'temporary_download_dir'
  output_file_name: 'bottom_features.nc' # the default output file name (if not specified)